apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-vneg
  namespace: svatares-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:9d27e98c24f25eccbeb9e1056e42d5ed97342e40960ba6a1860d8e543386a6cc
        name: my-go
        resources: {}
status: {}
